services:

  cobalt:
    image: ghcr.io/imputnet/cobalt:11
    restart: unless-stopped
    init: true
    read_only: true
    ports:
      - "9000:9000"
    environment:
      - API_URL=http://cobalt:9000/
      - CORS_WILDCARD=1

  bot:
    build: .
    restart: unless-stopped
    depends_on:
      - cobalt
    environment:
      - BOT_TOKEN=8772542821:AAFuF6-bH_PoFfOzOSjAzgx2uErihcomB-U
      - COBALT_API_URL=http://cobalt:9000
    volumes:
      - ./downloads:/root/instagram_downloads
      - ./data:/app/data
    working_dir: /app
